### ISSUE TITLE
exit_status for CPU limits

### ISSUE THREAD

**Issue by mlindauer** [sfalkner/pynisher#4]
Hi,

I would like to use pynisher to limit the CPU time of algorithms called with Popen.
However, it looks like the exit_status is not correctly saved.

Please consider the following mini example:

```
import subprocess
import logging
import pynisher

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("Pynisher")

def run():
    p = subprocess.Popen("python -c \"for i in range(99999999): i += 1\"", shell=True)
    p.communicate()

obj = pynisher.enforce_limits(cpu_time_in_s=3, logger=logger)(run)
result = obj()
print(obj.exit_status, obj.wall_clock_time)
```

The output is:

```
DEBUG:Pynisher:Restricting your function to 3 seconds cpu time.
DEBUG:Pynisher:Allowing a grace period of 0 seconds.
DEBUG:Pynisher:Function called with argumen: (), {}
DEBUG:Pynisher:call function
Killed
DEBUG:Pynisher:function returned properly: (None, 0)
DEBUG:Pynisher:return value: (None, 0)
0 3.0027379989624023
```

I would guess that the process is killed by a SIGKILL and not by SIGXCPU (as written in the pynisher code).

Using `grace_period_in_s=1` prevents the SIGKILL but the exit_status is still 0.

Playing with your code, I found that 
the pynisher thinks the process was killed with SIGCHLD (17)
but catching the signal in the process (here the python process opened with Popen), it is indeed 24 (SIGXCPU).

Do you have any idea how to fix this problem?

Cheers,
Marius

**Comment by sfalkner** [comment]
Hey Marius,

using your mini example I can reproduce your behaviour. Several notes:
1. SIGCHLD is usually ignored, so I would be surprised if that is the reason any of the processes involved died.
2. The problem is the shell=True argument. It actually catches the signal in your subprocess and the pynischer's subprocess doesn't get notified. You can see actually see that the p.communicate() returns normally and the exitcode of the process is -9 indicating that signal 9 was caught.
3. You actually solved the problem yourself in SpySMAC already.

**Comment by mlindauer** [comment]
Hi Stefan,

sorry, but I still don't know the solution for this issue.
Even without shell=True, I don't get the expected CpuTimeoutException.
Pynisher still returns:

`DEBUG:Pynisher:function returned properly: (None, 0)`

> You actually solved the problem yourself in SpySMAC already.

I did? 
I checked the SpySMAC code again. Indeed, the Popen does not use shell=True but besides this, I don't see why this should work there and in my example above not.

Cheers,
Marius

**Comment by sfalkner** [comment]
Hey Marius,

you are right, SpySMAC can infer the timeout by checking the output of the solver for UN-/SAT. I am afraid that there is no solution to your problem with the pynisher at this point. The subprocess will actually use a fork/execute on linux, deleting all the signal handlers in place.

You can recover the CPU timeout (but not the out-of-memory) with the following code:

```
import subprocess
import signal
import logging
import pynisher

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("Pynisher")

def run():
    p = subprocess.Popen("dd if=/dev/zero of=/dev/null".split(), shell=False)
    p.communicate()
    if p.returncode == -signal.SIGXCPU:
        raise pynisher.limit_function_call.CpuTimeoutException
    if p.returncode < 0:
        raise pynisher.limit_function_call.AnythingException
    return(0)


obj = pynisher.enforce_limits(cpu_time_in_s=1, logger=logger, grace_period_in_s=1)(run)
result = obj()
print(obj.exit_status, obj.wall_clock_time)
```

Without a grace period, you will not see the CpuTimeoutException, because the process gets killed with a SIGKILL immediately, without receiving a SIGXCPU which triggers that exception.

Hope that helps,

Stefan

**Comment by mlindauer** [comment]
Thanks! This should help.
Since my code is on my home machine (not not pushed to my online repo), I cannot try it today, but hopefully tomorrow.
